export enum BlueprintsActionTypes {
  SET_BLUEPRINTS_REQUEST = 'SET_BLUEPRINTS_REQUEST',
  SET_BLUEPRINTS_LOADING = 'SET_BLUEPRINTS_LOADING',
  BLUEPRINTS_REQUEST_SUCCESS = 'BLUEPRINTS_REQUEST_SUCCESS',
  BLUEPRINTS_REQUEST_FAILURE = 'BLUEPRINTS_REQUEST_FAILURE'
}
