export enum RewardActionTypes {
  SET_REWARDS_LOADING = 'SET_REWARDS_LOADING',
  SET_REWARDS_REQUEST = 'SET_REWARDS_REQUEST',
  REWARDS_REQUEST_SUCCESS = 'REWARDS_REQUEST_SUCCESS',
  REWARDS_REQUEST_FAILURE = 'REWARDS_REQUEST_FAILURE'
}
