export enum AssignedCardsActionTypes {
  SET_ASSIGNED_CARDS_REQUEST = 'SET_ASSIGNED_CARDS_REQUEST',
  SET_ASSIGNED_CARDS_LOADING = 'SET_ASSIGNED_CARDS_LOADING',
  ASSIGNED_CARDS_REQUEST_SUCCESS = 'ASSIGNED_CARDS_REQUEST_SUCCESS',
  ASSIGNED_CARDS_REQUEST_FAILURE = 'ASSIGNED_CARDS_REQUEST_FAILURE'
}
