export enum StacksActionsTypes {
  SET_STACKS_LOADING = 'SET_STACKS_LOADING',
  SET_STACKS_REQUEST = 'SET_STACKS_REQUEST',
  SET_STACKS_SUCCESS = 'SET_STACKS_SUCCESS',
  SET_STACKS_FAILURE = 'SET_STACKS_FAILURE',
  ASSIGN_CARD_TO_USER_SUCCESS = 'ASSIGN_CARD_TO_USER_SUCCESS',
}
